---
# tasks file for docker-compose

- name: Install pip
  apt:
    name: python3-pip
    update_cache: yes
    state: present

- name: Install docker packages
  remote_user: root
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker
- name: Add Docker s official GPG key
  remote_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker
- name: Verify that we have the key with the fingerprint
  remote_user: root
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker
- name: Set up the stable repository
  remote_user: root
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    update_cache: yes
  tags:
    - docker
- name: Update apt packages
  remote_user: root
  apt:
    update_cache: yes
  tags:
    - docker
- name: Install docker
  remote_user: root
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  #notify: Start docker on boot
  tags:
    - docker
- name: Add remote "root" user to "docker" group
  remote_user: root
  user:
    name: "root"
    groups: ["docker"]
    append: yes
  tags:
    - docker

- name: Install docker-compose
  remote_user: root
  get_url: 
    url : https://github.com/docker/compose/releases/download/v2.28.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'